### ISSUE TITLE
Build failed with Crystal 1.8.0

### ISSUE THREAD

**Issue by mamantoha** [I3oris/ic#16]
```
make
mkdir -p bin
CRYSTAL_CONFIG_PATH='$ORIGIN/../share/crystal-ic/src' CRYSTAL_PATH=lib:/mnt/disk/ruby/crystal/ic/share/crystal-ic/src crystal build -Dpreview_mt --progress src/ic.cr -o bin/ic
Showing last frame. Use --error-trace for full trace.

In share/crystal-ic/lib/reply/src/term_cursor.cr:6:5

 6 | ESC      = "\e"
     ^--
Error: already initialized constant Reply::Term::Cursor::ESC
```

```
crystal -v
Crystal 1.8.0 [14bfa992e] (2023-04-14)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

This is because the Crystal 1.8.0 release already includes some libraries that were originally from this shard.

**Comment by straight-shoota** [comment]
This is due to https://github.com/crystal-lang/crystal/pull/13315
Previous to 1.8.0 the compiler used `require "reply"` which would resolve to the `reply` shard installed in the local `lib` folder, which is the same as any other `require "reply"` in ic. Now the compiler explicitly requires the relative path to the vendored copy of the `reply` which differs and thus conflicts with an locally installed copy.

**Comment by straight-shoota** [comment]
Yes, that would cause problems. But it would at least offer some flexibility to use different versions as long as they are compatible. Or maybe even monkeypatch compatibility patches.

**Comment by I3oris** [comment]
@mamantoha which are your version of IC? Following crystal-lang/crystal#13315 I faced the same issue than you. I should have fixed that in the last version of IC, in which I removed the shard dependency on REPLy. Now it uses only one single version, the one in the compiler.

Note you can do a `shard prune` to clean the unused version.

**Comment by mamantoha** [comment]
@I3oris latest from `master` branch.

I cloned this repository from Github.
`cd ic` and make.
`shards prune` - the same error

**Comment by I3oris** [comment]
Then that weird. I should have missed something.. Thank you for the issue then!

**Comment by straight-shoota** [comment]
It shouldn't matter if `reply` is installed in `./lib`. The important part is that there should be no `require "reply"`.

**Comment by I3oris** [comment]
Yes there is no occurrence of `require "reply"` anymore.

Sorry but I cannot reproduce. I tested on the latest docker `crystallang/crystal` and `IC` compiles fine: 
```
root@d09d47ce2312:/# apt-get update && apt-get install llvm llvm-dev g++
...
root@d09d47ce2312:/# crystal -v
Crystal 1.8.0 [14bfa992e] (2023-04-14)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
root@d09d47ce2312:/# 
root@d09d47ce2312:/# git clone https://github.com/I3oris/ic.git
Cloning into 'ic'...
remote: Enumerating objects: 5086, done.
remote: Counting objects: 100% (1867/1867), done.
remote: Compressing objects: 100% (1156/1156), done.
remote: Total 5086 (delta 912), reused 1198 (delta 622), pack-reused 3219
Receiving objects: 100% (5086/5086), 4.92 MiB | 895.00 KiB/s, done.
Resolving deltas: 100% (2527/2527), done.
root@d09d47ce2312:/# 
root@d09d47ce2312:/# cd ic
root@d09d47ce2312:/ic# 
root@d09d47ce2312:/ic# make
g++ -c  -o /ic/share/crystal-ic/src/llvm/ext/llvm_ext.o /ic/share/crystal-ic/src/llvm/ext/llvm_ext.cc -I/usr/lib/llvm-14/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
mkdir -p bin
CRYSTAL_CONFIG_PATH='$ORIGIN/../share/crystal-ic/src' CRYSTAL_PATH=lib:/ic/share/crystal-ic/src crystal build -Dpreview_mt --progress src/ic.cr -o bin/ic
root@d09d47ce2312:/ic#                                
root@d09d47ce2312:/ic# bin/ic -v
Version: 0.7.0
Crystal version: 1.8.0
REPLy version: 0.3.0
root@d09d47ce2312:/ic#
```

@mamantoha maybe you miss the lasted version because I released it the same day you raise the issue? The version should be 0.7.0.

**Comment by mamantoha** [comment]
@I3oris to summarize, I tested the build on different systems and found that there is an issue on Arch Linux, whereas it works fine on Ubuntu and macOS. Closing for now.

**Comment by mamantoha** [comment]
@I3oris I was able to identify the root cause of the issue. The "ic" repository was cloned to "/mnt/disk/ruby/crystal/ic", and "/mnt/disk/ruby" was symlinked to "/ruby". When attempting to run "make" from "~/ruby/crystal/ic", it resulted in an error. However, running "make" from "/mnt/disk/ruby/crystal/ic" was successful.

**Comment by I3oris** [comment]
oh good!

I reproduce too with a symlink. Looking that a bit deeper, it's seem that the `require "../share/crystal-ic/lib/reply/src/reply"` in `src/repl_readers.cr`  and the `require "../../../../lib/reply/src/reply"` in `share/crystal-ic/src/compiler/crystal/interpreter/repl_reader.cr` is not considered the same file when running from a symlink, so it requires twice and errors.

Maybe a crystal issue but hasn't found a reduced case of this, but It seems appear only if `CRYSTAL_PATH` is modified.

**Comment by straight-shoota** [comment]
https://github.com/crystal-lang/crystal/issues/12969

**Comment by I3oris** [comment]
It turns out that the `require "../share/crystal-ic/lib/reply/src/reply"` is now useless. That should fully solve the issue.

**Comment by mamantoha** [comment]
@I3oris thanks!
