### ISSUE TITLE
broken on Crystal 1.12

### ISSUE THREAD

**Issue by zw963** [I3oris/ic#21]
Thanks

**Comment by I3oris** [comment]
It works fine on 1.12 on my side. Could you please share more details about what's wrong?

**Comment by zw963** [comment]
Sorry, my fault, the issue caused my i add a new path into `CRYSTAL_PATH`, which there have several library i `require it` manually frequently, which cause following formatting issue.

![image](https://github.com/I3oris/ic/assets/549126/4e27f6a0-25b8-40a9-897a-e5925d5cd59a)

Following is shell wrapper which how to use `cr i`.

![image](https://github.com/I3oris/ic/assets/549126/0e19fe4a-e224-4c03-9375-a6f91dc6bf5e)

there only several live in the above added CRYSTAL_PATH

```
 ╰─ $ ls
debug/  debug.cr  fiber_debug.cr  meta.cr

(1b0375b99) master *$%  ➦
 ╰─ $ pwd
/home/zw963/Dropbox/common/crystal/lib
```
